apiVersion: v1
kind: Secret
metadata:
  name: mecm-fe-secret
  labels:
    app: mecm-fe-secret
type: Opaque
stringData:
  clientId: {{ .Values.global.oauth2.clients.mecm.clientId }}
  clientSecret: {{ .Values.global.oauth2.clients.mecm.clientSecret }}