apiVersion: v1
kind: Secret
metadata:
  name: appstore-fe-secret
  labels:
    app: appstore-fe-secret
type: Opaque
stringData:
  clientId: {{ .Values.global.oauth2.clients.appstore.clientId }}
  clientSecret: {{ .Values.global.oauth2.clients.appstore.clientSecret }}