apiVersion: v1
kind: Service
metadata:
  name: tool-chain-svc
  labels:
    svc: tool-chain-svc
spec:
  ports:
    - port: 8059
      targetPort: 8059
      protocol: TCP
  selector:
    app: tool-chain