{{- if .Values.appstoreBe.appdtranstool.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdtranstool
spec:
  selector:
    matchLabels:
      app: appdtranstool
  replicas: 1
  template:
    metadata:
      labels:
        app: appdtranstool
    spec:
      containers:
        - name: appdtranstool
          image: {{ .Values.images.appdtranstool.repository }}:{{ .Values.images.appdtranstool.tag }}
          imagePullPolicy: {{ .Values.images.appdtranstool.pullPolicy }}
          ports:
            - containerPort: 8765
          env:
            - name: LOG_DIR
              value: /usr/app/log
            - name: SSL_ENABLED
              value: {{ quote .Values.global.ssl.enabled }}
            {{- if .Values.global.ssl.enabled }}
            - name: SSL_KEY_STORE_PATH
              value: /usr/app/ssl/keystore.p12
            - name: SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keystorePassword
            - name: SSL_KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keystoreType
            - name: SSL_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keyAlias
            {{- end }}
          volumeMounts:
            {{- if .Values.global.persistence.enabled }}
            - name: appdtranstool-log
              mountPath: /usr/app/log
            {{- end }}
            {{- if .Values.global.ssl.enabled }}
            - mountPath: /usr/app/ssl
              name: appdtranstool-keystore
            {{- end }}
      volumes:
        {{- if .Values.global.persistence.enabled }}
        - name: appdtranstool-log
          persistentVolumeClaim:
            claimName: appdtranstool-log-pvc
        {{- end }}
        {{- if .Values.global.ssl.enabled }}
        - name: appdtranstool-keystore
          secret:
            secretName: {{ .Values.global.ssl.secretName }}
            items:
              - key: keystore.p12
                path: keystore.p12
        {{- end }}
{{- if .Values.global.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdtranstool-log-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}
