apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mepm-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
#ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
  - secretName: {{ .Values.global.ingress.tls.secretName }}
  rules:
  -  http:
       paths:
       - path: /?(.*)
         pathType: Prefix
         backend:
           service:
             name: mepm-fe
             port:
               number: 8200
       - path: /lcmcontroller
         pathType: Prefix
         backend:
           service:
             name: mecm-mepm-lcmcontroller
             port:
               number: 8094
       - path: /apprulemgr
         pathType: Prefix
         backend:
           service:
             name: mecm-mepm-apprulemgr
             port: 
               number: 8096
       - path: /rescontroller
         pathType: Prefix
         backend:
           service:
             name: mecm-mepm-rescontroller
             port:
               number: 8098
