{{- if .Values.global.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-datastore-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.dnsserver.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mep-datastore-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mep.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-datastore-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-datastore-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mep-log-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mepauth-log-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-log-pvc
  namespace: mep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
