apiVersion: v1
kind: Service
metadata:
  name: appstore-be-svc
  labels:
    svc: appstore-be-svc
spec:
  ports:
    - port: {{ .Values.expose.appstoreBe.port }}
      targetPort: 8099
      protocol: TCP
  selector:
    app: appstore-be
---
apiVersion: v1
kind: Service
metadata:
  name: appstore-be-postgres-svc
  labels:
    svc: appstore-be-postgres-svc
spec:
  ports:
    - port: {{ .Values.expose.postgres.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: appstore-be-postgres