############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: v1
kind: Secret
metadata:
  name: appstore-be-secret
  labels:
    app: appstore-be-secret
type: Opaque
stringData:
  postgresUsername: {{ .Values.postgres.username }}
  postgresPassword: {{ .Values.postgres.password }}
  appstoreRepoUserName: {{ .Values.appstoreBe.dockerRepo.appstore.username }}
  appstoreRepoPassword: {{ .Values.appstoreBe.dockerRepo.appstore.password }}
  devRepoUserName: {{ .Values.appstoreBe.dockerRepo.developer.username }}
  devRepoPassword: {{ .Values.appstoreBe.dockerRepo.developer.password }}