apiVersion: v1
kind: Secret
metadata:
  name: appstore-be-secret
  labels:
    app: appstore-be-secret
type: Opaque
stringData:
  postgresUsername: {{ .Values.postgres.username }}
  postgresPassword: {{ .Values.postgres.password }}