############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


global:
  persistence:
    enabled: true
    storageClassName: nfs-client
images:
  mep:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep
    tag: latest
    pullPolicy: IfNotPresent
  mepauth:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepauth
    tag: latest
    pullPolicy: IfNotPresent
  kong:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/kong
    tag: 2.0.4-ubuntu
    pullPolicy: IfNotPresent
  postgres:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent
  dns:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep-dns-server
    tag: latest
    pullPolicy: IfNotPresent
  elasticsearch:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/elasticsearch
    tag: 7.9.0
    pullPolicy: IfNotPresent
  ntp:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/cturra/ntp
    tag: latest
    pullPolicy: IfNotPresent

dnsserver:
  command: [ ]
  storageSize: 1Gi

mep:
  storageSize: 1Gi

elasticsearch:
  storageSize: 1Gi

postgres:
  username: kong
  dbname: kongdb
  kongPass:
  storageSize: 1Gi

mepauthProperties:
  jwtPrivateKey:

ssl:
  enabled: false
  secretName:

networkIsolation:
  ipamType: host-local
  phyInterface:
    mp1: ens3
    mm5: ens3

livenessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

mepAuthLivenessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 30

mepAuthReadinessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 30

mepConfig:
  dnsAgentType: all
  dataPlaneType: none

ntpConfig:
  servers: "cn.pool.ntp.org, asia.pool.ntp.org, pool.ntp.org"

