apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecm-mepm-k8splugin
  namespace: default
  labels:
    app: mecm-mepm-k8splugin
spec:
  selector:
    matchLabels:
      app: mecm-mepm-k8splugin
  replicas: 1
  template:
    metadata:
      labels:
        app: mecm-mepm-k8splugin
    spec:
      initContainers:
        - name: check-db-ready
          image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
          command: ['sh', '-c', 'until pg_isready -h  mepm-postgres -p 5432; do echo waiting for database; sleep 2; done;'] 
      containers:
        - image: {{ .Values.images.k8splugin.repository }}:{{ .Values.images.k8splugin.tag }}
          imagePullPolicy: {{ .Values.images.k8splugin.pullPolicy }}
          name: mecm-mepm-k8splugin
          env:
            - name: LOG_DIR
              value: /var/log/k8splugin
            - name: LISTEN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP    
            - name: K8S_PLUGIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mepm.secretName }}
                  key: postgresk8sPluginPassword
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.publicKeySecretName }}
                  key: publicKey
          ports:
            - containerPort: 8095
          resources: {}
          volumeMounts:

            - mountPath: /usr/app/ssl
              name: k8splugin-certs
              readOnly: true

            {{- if .Values.persistence.enabled }}
            - name: k8splugin-log
              mountPath: /var/log/k8splugin
            {{- end }}
      volumes:

        - name: k8splugin-certs
          secret:
            secretName: {{ .Values.ssl.secretName }}
            items:
              - key: ca.crt
                path: ca.crt
                mode: 0644
              - key: server_tls.crt
                path: server_tls.crt
                mode: 0644
              - key: server_tls.key
                path: server_tls.key
                mode: 0644
        {{- if .Values.persistence.enabled }}
        - name: k8splugin-log
          hostPath:
            path: /var/log/edgegallery/k8splugin
        {{- end }}


