############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-center
  labels:
    app: service-center
spec:
  selector:
    matchLabels:
      app: service-center
  replicas: 1
  template:
    metadata:
      labels:
        app: service-center
    spec:
      containers:
        - name: service-center
          image: {{ .Values.images.repository }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 30100
      {{- if .Values.global.ssl.enabled }}
          env:
            - name: SSL_ROOT
              value: /opt/service-center/ssl
          volumeMounts:
            - mountPath: /opt/service-center/start.sh
              name: service-center-conf
              subPath: start.sh
            - mountPath: /opt/service-center/ssl
              name: service-center-ssl
      volumes:
        - name: service-center-conf
          configMap:
            name: service-center-configmap
            defaultMode: 0500
        - name: service-center-ssl
          secret:
            secretName: {{ .Values.global.ssl.secretName }}
            items:
              - key: trust.cer
                path: trust.cer
                mode: 0644
              - key: server.cer
                path: server.cer
                mode: 0644
              - key: server_key.pem
                path: server_key.pem
                mode: 0644
              - key: cert_pwd
                path: cert_pwd
                mode: 0644
      {{- end }}