global:
  servicecenter:
    enabled: true
  usermgmt:
    enabled: true
  appstore:
    enabled: true
  developer:
    enabled: true
  mecm-fe:
    enabled: true
  mecm-mepm:
    enabled: true
  mecm-meo:
    enabled: true
  persistence:
    enabled: true
    storageClassName: nfs-client
  ingress:
    enabled: true
    tls:
      enabled: true
      secretName: edgegallery-ingress-secret
    annotations:
      bodySize: 20m
    hosts:
      auth: auth.edgegallery.org
      developer: developer.edgegallery.org
      appstore: appstore.edgegallery.org
      mecm: mecm.edgegallery.org
      atp: atp.edgegallery.org
      lab: lab.edgegallery.org
  ssl:
    enabled: true
    secretName: edgegallery-ssl-secret
  oauth2:
    authServerAddress: https://auth.edgegallery.org
    clients:
      appstore:
        clientId: appstore-fe
        clientSecret:
        clientUrl: https://appstore.edgegallery.org
      developer:
        clientId: developer-fe
        clientSecret:
        clientUrl: https://developer.edgegallery.org
      mecm:
        clientId: mecm-fe
        clientSecret:
        clientUrl: https://mecm.edgegallery.org
      atp:
        clientId: atp-fe
        clientSecret:
        clientUrl: https://atp.edgegallery.org
      lab:
        clientId: lab-fe
        clientSecret:
        clientUrl: https://lab.edgegallery.org
jwt:
  secretName: user-mgmt-jwt-secret
  sms:
    enabled: true
    url: https://rtcsms.cn-north-1.myhuaweicloud.com:10743/sms/batchSendSms/v1
    appKey: zES2FDR1z0sOM8jT8uFs0uUzP4Wl
    appSecret: WBGhdH3JlQyu9JjX9wENW5flB7Gg
    sender: '8820031341626'
    templateId: 3f08b042a9d44cb8ad3c71c44e0f1cf8
    signature: MEC
    statusCallBack: MEC

images:
  usermgmt:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/user-mgmt
    tag: latest
    pullPolicy: Always
  redis:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/redis
    tag: 6.0.3
    pullPolicy: IfNotPresent
  initservicecenter:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/curl
    tag: 7.75.0
    pullPolicy: IfNotPresent
  appstoreBe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-be
    tag: latest
    pullPolicy: Always
  appstoreFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-fe
    tag: latest
    pullPolicy: Always
  developerBe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-be
    tag: latest
    pullPolicy: Always
  developerFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-fe
    tag: latest
    pullPolicy: Always
  toolChain:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/tool-chain
    tag: latest
    pullPolicy: Always
  portingAdvisor:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/porting-advisor
    tag: latest
    pullPolicy: IfNotPresent
  atp:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/atp-be
    tag: latest
    pullPolicy: Always
  atpFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/atp-fe
    tag: latest
    pullPolicy: Always
  mecmFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-fe
    tag: latest
    pullPolicy: Always
  service-center:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/service-center
    tag: latest
    pullPolicy: Always

  inventory:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-inventory
    tag: latest
    pullPolicy: Always
  appo:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appo
    tag: latest
    pullPolicy: Always
  apm:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apm
    tag: latest
    pullPolicy: Always
  postgres:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent

# appShare config
appShare:
  enabled: true
  platformName: EdgeGallery AppStore
  platformUrl: http://127.0.0.1:8099
  atpReportUrl: http://127.0.0.1:8073/atpreport?taskid=%s
