############################################################################
# Copyright 2020-2021 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


global:
  ingress:
    enabled: false
  ssl:
    enabled: false
    secretName:
  persistence:
    enabled: true
    storageClassName: nfs-client
  oauth2:
    authServerAddress:
    authServerAddressClientAccess:
    redirectUriParam:
    clients:
      developer:
        clientId: developer-fe
        clientSecret:
images:
  developerFe:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/developer-fe
    tag: latest
    pullPolicy: Always
  developerBe:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/developer-be
    tag: latest
    pullPolicy: Always
  toolChain:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery//tool-chain
    tag: latest
    pullPolicy: IfNotPresent
  portingAdvisor:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/porting-advisor
    tag: latest
    pullPolicy: IfNotPresent
  postgres:
    repository: swr.cn-north-4.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent
  initservicecenter:
    repository: swr.cn-north-4.myhuaweicloud.com/eg-common/curl
    tag: 7.75.0
    pullPolicy: IfNotPresent
postgres:
  username: developer
  password: 
  dbname: developerdb
expose:
  developerFe:
    port: 8443
    nodePort: 30092
  # vnc
  developerBe:
    port: 9082
    nodePort: 30098
    vncPort1: 30111
    vncNodePort1: 30111
    vncPort2: 30112
    vncNodePort2: 30112
    vncPort3: 30113
    vncNodePort3: 30113
    vncPort4: 30114
    vncNodePort4: 30114
    vncPort5: 30115
    vncNodePort5: 30115
    vncPort6: 30116
    vncNodePort6: 30116
    vncPort7: 30117
    vncNodePort7: 30117
    vncPort8: 30118
    vncNodePort8: 30118
    vncPort9: 30119
    vncNodePort9: 30119
    vncPort10: 30120
    vncNodePort10: 30120
  postgres:
    port: 5432

developer:
  developerBeIp:
  secretName: edgegallery-signature-secret
  dockerRepo:
    endpoint: 
    project: developer
    password: 
    username:
  vmImage:
    fileSystemAddress: 
  toolChain:
    enabled: false
    
# probe configuration parameters
livenessProbe:
  path: /health
  scheme: HTTPS
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  FailureThreshold: 3
readinessProbe:
  path: /health
  scheme: HTTPS
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5

  
  
  
  