############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-postgres
  namespace: default
spec:
  selector:
    matchLabels:
      app: filesystem-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: filesystem-postgres
    spec:
      containers:
        - name: filesystem-postgres
          image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_DB_NAME
              value: {{ .Values.postgres.dbname }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          volumeMounts:
            {{- if .Values.global.persistence.enabled }}
            - mountPath: /var/lib/postgresql/data
              name: filesystem-postgres-data
            {{- end }}
      volumes:
        {{- if .Values.global.persistence.enabled }}
        - name: filesystem-postgres-data
          persistentVolumeClaim:
            claimName: filesystem-postgres-pvc
        {{- end }}
 
{{- if .Values.global.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filesystem-postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 5Gi
{{- end }} 
---
apiVersion: v1
kind: Service
metadata:
  name: filesystem-postgres
  labels:
    svc: filesystem-postgres
    
spec:
  ports:
    - port: {{ .Values.expose.postgres.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: filesystem-postgres
