############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


global:
  ingress:
    enabled: false
  ssl:
    enabled: false
    secretName:
  persistence:
    enabled: false
    storageClassName: nfs-client
  oauth2:
    clients:
      appstore:
        clientId: appstore-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      developer:
        clientId: developer-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      mecm:
        clientId: mecm-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      atp:
        clientId: atp-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      lab:
        clientId: lab-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
jwt:
  secretName:
expose:
  port: 8067
  nodePort: 30067
images:
  usermgmt:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/user-mgmt
    tag: latest
    pullPolicy: Always
  postgres:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent
  redis:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/redis
    tag: 6.0.3
    pullPolicy: IfNotPresent
  initservicecenter:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/curl
    tag: 7.75.0
    pullPolicy: IfNotPresent
postgres:
  username: usermgmt
  password: te9Fmv%qaq
  dbname: usermgmtdb
cors:
  allowOrigins: "*"
redis:
  password: te9Fmv%qaq
  timeout: 1800
  verificationTimeout: 300
  maxTotal: 1000
  maxIdle: 50
  maxWaitMillis: 100000
sms:
  enabled: false
  url:
  appKey:
  appSecret:
  sender:
  templateId:
  signature:
  statusCallBack:
mail:
  enabled: false
  host:
  port: 25
  sender:
  authCode:

# probe configuration parameters
livenessProbe:
  path: /health
  scheme: HTTPS
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  FailureThreshold: 3
readinessProbe:
  path: /health
  scheme: HTTPS
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
