apiVersion: v1
kind: Secret
metadata:
  name: user-mgmt-secret
  labels:
    app: user-mgmt
type: Opaque
stringData:
  postgresUsername: {{ .Values.postgres.username }}
  postgresPassword: {{ .Values.postgres.password }}
  redisPassword: {{ .Values.redis.password }}
  appstoreClientId: {{ .Values.global.oauth2.clients.appstore.clientId }}
  appstoreClientSecret: {{ .Values.global.oauth2.clients.appstore.clientSecret }}
  appstoreClientUrl: {{ .Values.global.oauth2.clients.appstore.clientUrl }}
  developerClientId: {{ .Values.global.oauth2.clients.developer.clientId }}
  developerClientSecret: {{ .Values.global.oauth2.clients.developer.clientSecret }}
  developerClientUrl: {{ .Values.global.oauth2.clients.developer.clientUrl }}
  mecmClientId: {{ .Values.global.oauth2.clients.mecm.clientId }}
  mecmClientSecret: {{ .Values.global.oauth2.clients.mecm.clientSecret }}
  mecmClientUrl: {{ .Values.global.oauth2.clients.mecm.clientUrl }}
  {{- if .Values.sms.enabled }}
  smsUrl: {{ .Values.sms.url }}
  smsAppKey: {{ .Values.sms.appKey }}
  smsAppSecret: {{ .Values.sms.appSecret }}
  smsSender: {{ quote .Values.sms.sender }}
  smsTemplateId: {{ .Values.sms.templateId }}
  smsAppSignature: {{ .Values.sms.signature }}
  smsStatusCallBack: {{ .Values.sms.statusCallBack }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-mgmt-redis-secret
  labels:
    app: user-mgmt-redis
type: Opaque
stringData:
  redis.conf: |
    requirepass {{ .Values.redis.password }}