apiVersion: v1
kind: Service
metadata:
  name: mecm-appo
  labels:
    app: mecm-appo
spec:
  selector:
    app: mecm-appo
  type: NodePort
  ports:
    - port: {{ .Values.expose.appo.port }}
      targetPort: 8091
      nodePort: {{ .Values.expose.appo.nodePort }}
