############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecm-mepm-apprulemgr
  namespace: default
  labels:
    app: mecm-mepm-apprulemgr
spec:
  selector:
    matchLabels:
      app: mecm-mepm-apprulemgr
  replicas: 1
  template:
    metadata:
      labels:
        app: mecm-mepm-apprulemgr
    spec:
      initContainers:
        - name: check-db-ready
          image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
          command: ['sh', '-c', 'until pg_isready -h  mepm-postgres -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - image: {{ .Values.images.apprulemgr.repository }}:{{ .Values.images.apprulemgr.tag }}
          imagePullPolicy: {{ .Values.images.apprulemgr.pullPolicy }}
          name: mecm-mepm-apprulemgr
          livenessProbe:
            httpGet:
              path: /apprulemgr/v1/health
              port: {{ .Values.expose.apprulemgr.port }}
              scheme: {{ .Values.livenessProbe.scheme}}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds}}
            successThreshold: {{ .Values.livenessProbe.successThreshold}}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold}}

          readinessProbe:
            httpGet:
              path: /apprulemgr/v1/health
              port: {{ .Values.expose.apprulemgr.port }}
              scheme: {{ .Values.readinessProbe.scheme}}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds}}
          env:
            - name: LOG_DIR
              value: /usr/app/log
            - name: MEP_SERVER_ADDR
              value: mep-mm5.mep
            - name: MEP_SERVER_PORT
              value: "80"
            - name: APPRULEMGR_DB_ADAPTER
              value: pgDb
            - name: IS_HTTPS
              value: "false"
            - name: LISTEN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.publicKeySecretName }}
                  key: publicKey
            - name: APPRULEMGR_DB_PASSWORD
              value: {{ .Values.mepm.postgres.apprulemgrDbPass }}

          ports:
            - containerPort: 8096
          resources: {}
          volumeMounts:
            - mountPath: /usr/app/ssl/
              name: apprulemgr-certs
              readOnly: true
            {{- if .Values.global.persistence.enabled }}
            - mountPath: /usr/app/log
              name: apprulemgr-log
            {{- end }}
      volumes:
        - name: apprulemgr-certs
          secret:
            secretName: {{ .Values.global.ssl.secretName }}
            items:
              - key: ca.crt
                path: ca.crt
                mode: 0644
              - key: server_tls.crt
                path: server_tls.crt
                mode: 0644
              - key: server_tls.key
                path: server_tls.key
                mode: 0644
        {{- if .Values.global.persistence.enabled }}
        - name: apprulemgr-log
          persistentVolumeClaim:
            claimName: apprulemgr-log-pvc
        {{- end }}
{{- if .Values.global.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprulemgr-log-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
