###########################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: v1
kind: ConfigMap
metadata:
  name: atp-postgres-initdb-configmap
data:
  postgres.sql: |
    CREATE TABLE TASK_TABLE (
        ID                       VARCHAR(200)       NOT NULL,
        APPNAME                  VARCHAR(200)       NULL,
        APPVERSION               VARCHAR(200)       NULL,
        STATUS                   VARCHAR(200)       NULL,
        TESTCASEDETAIL           TEXT               NULL,
        CREATETIME               TIMESTAMP          NULL,
        ENDTIME                  TIMESTAMP          NULL,
        PROVIDERID               VARCHAR(200)       NULL,
        PACKAGEPATH              VARCHAR(200)       NULL,
        USERID                   VARCHAR(200)       NULL,
        USERNAME                 VARCHAR(200)       NULL,
        CONSTRAINT task_table_pkey PRIMARY KEY (ID)
    );

    CREATE TABLE TEST_CASE_TABLE (
        ID                       VARCHAR(200)       NOT NULL,
        NAME                     VARCHAR(200)       NULL,
        TYPE                     VARCHAR(200)       NULL,
        CLASSNAME                VARCHAR(200)       NULL,
        HASHCODE                 TEXT               NULL, 
        DESCRIPTION              TEXT               NULL,
        FILEPATH                 VARCHAR(200)       NULL,
        CODELANGUAGE             VARCHAR(200)       NULL,
        EXPECTRESULT             VARCHAR(200)       NULL,
        VERIFICATIONMODEL        VARCHAR(200)       NULL,
        CONSTRAINT test_case_table_pkey PRIMARY KEY (ID)
    );

    INSERT INTO public.test_case_table(
      id, name, hashCode,type, classname,  description,filePath,codeLanguage,expectResult,verificationModel)
      VALUES ('4d203173-1111-4f62-aabb-8ebcec357f87','Manifest File Path Validation','','complianceTest','org.edgegallery.atp.schedule.testcase.compliance.SuffixTestCase','Root path must contain the file which name ends of .mf','','java','there has .mf file in root path.','EdgeGallery,Mobile'),
      ('4d203173-2222-4f62-aabb-8ebcec357f87','Manifest File Field Validation','','complianceTest','org.edgegallery.atp.schedule.testcase.compliance.MFContentTestCase','.mf file must contain the following field: app_product_name, app_provider_id, app_package_version, app_release_date_time and app_package_description','','java','the requirement fileds must exist.','EdgeGallery,Unicom'),
      ('4d203173-3333-4f62-aabb-8ebcec357f87','Manifest File Source Path Validation','','complianceTest','org.edgegallery.atp.schedule.testcase.compliance.SourcePathTestCase','The value of Source filed must be right path, the corresponding file must exist','','java','the value of source must right path.','EdgeGallery,Telecom'),
      ('4d203173-4444-4f62-aabb-8ebcec357f87','Tosca File Validation','','complianceTest','org.edgegallery.atp.schedule.testcase.compliance.TOSCAFileTestCase','TOSCA.meta file must exist, and it must contain the field: Entry-Definitions, and the the value of the filed must be right path, the corresponding file must exist','','java','tosca file is right.','EdgeGallery,Definition'),
      ('4d203173-5555-4f62-aabb-8ebcec357f87','Instantiate Application','','sandboxTest','org.edgegallery.atp.schedule.testcase.sandbox.InstantiateAppTestCase','Instantiate application and its dependency application on one edge host','','java','app can instantiate successfully.','EdgeGallery,Mobile'),
      ('4d203173-6666-4f62-aabb-8ebcec357f87','UnInstantiate Application','','sandboxTest','org.edgegallery.atp.schedule.testcase.sandbox.UninstantiateAppTestCase','Uninstantiate application and its dependency application on one edge host','','java','app can uninstantiate successfully.','EdgeGallery,Mobile'),
      ('4d203173-7777-4f62-aabb-8ebcec357f87','Virus Scanning','','securityTest','org.edgegallery.atp.schedule.testcase.virusscan.VirusScanTestCase','Virus scan by clamav util','','java','app has no virus.','EdgeGallery,Mobile');