############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-fe
  namespace: default
  labels:
    app: lab-fe
spec:
  selector:
    matchLabels:
      app: lab-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: lab-fe
    spec:
      containers:
        - name: lab-fe
          image: {{ .Values.images.labFe.repository }}:{{ .Values.images.labFe.tag }}
          imagePullPolicy: {{ .Values.images.labFe.pullPolicy }}
          ports:
            - containerPort: 8443
          env:
            - name: LOG_FILE_NAME
              value: lab-fe
            - name: LISTEN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SC_ADDRESS
              value: http{{ if .Values.global.ssl.enabled }}s{{ end }}://service-center:30100
            - name: AUTH_SERVER_ADDRESS
              value: {{ .Values.global.oauth2.authServerAddress }}
            - name: COOKIE_NAME
              value: LABSESSIONID
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lab-fe-secret
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lab-fe-secret
                  key: clientSecret
            - name: SSL_ENABLED
              value: {{ quote .Values.global.ssl.enabled }}
            - name: IS_SECURE_BACKEND
              value: {{ quote .Values.global.ssl.enabled }}
            {{- if .Values.global.ssl.enabled }}
            - name: SSL_KEY_STORE_PATH
              value: /usr/app/ssl/keystore.p12
            - name: SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keystorePassword
            - name: SSL_KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keystoreType
            - name: SSL_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.ssl.secretName }}
                  key: keyAlias
            {{- end }}
          volumeMounts:
            {{- if .Values.global.ssl.enabled }}
            - mountPath: /usr/app/ssl
              name: lab-fe-keystore
            {{- end }}
      volumes:
        {{- if .Values.global.ssl.enabled }}
        - name: lab-fe-keystore
          secret:
            secretName: {{ .Values.global.ssl.secretName }}
            items:
              - key: keystore.p12
                path: keystore.p12
                mode: 0644
        {{- end }}