apiVersion: v1
kind: Service
metadata:
  name: api-emulator
  labels:
    app: api-emulator
spec:
  selector:
    app: api-emulator
  type: NodePort
  ports:
    - port: {{ .Values.expose.port }}
      targetPort: 8089
      nodePort: {{ .Values.expose.nodePort }}
