global:
  ingress:
    enabled: false
  ssl:
    enabled: false
    secretName:
  persistence:
    enabled: false
    storageClassName: nfs-client
  oauth2:
    authServerAddress:
    clients:
      appstore:
        clientId: appstore-fe
        clientSecret: te9Fmv%qaq
images:
  appstoreFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-fe
    tag: latest
    pullPolicy: IfNotPresent
  appstoreBe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-be
    tag: latest
    pullPolicy: IfNotPresent
  postgres:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres
    tag: 12.2
    pullPolicy: IfNotPresent
  initservicecenter:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/curl
    tag: latest
    pullPolicy: IfNotPresent
postgres:
  username: appstore
  password: te9Fmv%qaq
  dbname: appstoredb
expose:
  appstoreFe:
    port: 8443
    nodePort: 30091
  appstoreBe:
    port: 8099
    nodePort: 30099
  postgres:
    port: 5432