apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
  namespace: default
  labels:
    app: healthcheck
spec:
  selector:
    matchLabels:
      app: healthcheck
  replicas: 1
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: {{ .Values.images.healthcheck.repository }}:{{ .Values.images.healthcheck.tag }}
          imagePullPolicy: {{ .Values.images.healthcheck.pullPolicy }}
          ports:
            - containerPort: 9527
          env:
            - name: LOCAL_IP
              value: {{ .Values.healthcheck.localIp }}
          volumeMounts:
            {{- if .Values.global.persistence.enabled }}
            - name: healthcheck-log
              mountPath: /usr/mep/log
            {{- end }}
      volumes:
        {{- if .Values.global.persistence.enabled }}
        - name: healthcheck-log
          persistentVolumeClaim:
            claimName: healthcheck-log-pvc
        {{- end }}

{{- if .Values.global.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthcheck-log-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ quote .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: 1Gi
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: healthcheck-svc
  namespace: default
  labels:
    svc: healthcheck-svc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.expose.healthcheck.port }}
      targetPort: 9527
      protocol: TCP
      nodePort: {{ .Values.expose.healthcheck.nodePort }}
  selector:
    app: healthcheck
