############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


global:
  ingress:
    enabled: false
  ssl:
    enabled: true
    secretName: edgegallery-ssl-secret
  persistence:
    enabled: true
    storageClassName: nfs-client
  oauth2:
    authServerAddress:
    clients:
      mecm:
        clientId: mecm-fe
        clientSecret: 
        clientUrl: 
images:
  inventory:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/mecm-inventory
    tag: latest
    pullPolicy: IfNotPresent
  appo:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/mecm-appo
    tag: latest
    pullPolicy: IfNotPresent
  apm:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/mecm-apm
    tag: latest
    pullPolicy: IfNotPresent
  postgres:
    repository: swr.cn-north-4.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent
  mecmFe:
    repository: swr.cn-north-4.myhuaweicloud.com/edgegallery/mecm-fe
    tag: latest
    pullPolicy: IfNotPresent  
  initservicecenter:
    repository: swr.cn-north-4.myhuaweicloud.com/eg-common/service-center
    tag: latest
    pullPolicy: IfNotPresent
  curl:
    repository: swr.cn-north-4.myhuaweicloud.com/eg-common/curl
    tag: 7.75.0
    pullPolicy: IfNotPresent
    
persistence:
  enabled: true
expose:
  inventory:
    port: 8093
    nodePort: 30203
  appo:
    port: 8091
    nodePort: 30201
  apm:
    port: 8092
    nodePort: 30202
  postgres:
    port: 5432
  mecmFe:
    port: 8443
    nodePort: 30093

mecm:
  pushImage: true
  docker:
    fsgroup:
    dockerRepoUserName: admin
    dockerRepopassword: 
  repository:
    dockerRepoEndpoint: 127.0.0.1:30003
    sourceRepos:
  postgres:
    postgresPass:
    apmDbPass: 
    appoDbPass: 
    inventoryDbPass: 

 
# probe configuration parameters
livenessProbe:
  path: /health
  scheme: HTTPS
  initialDelaySeconds: 600
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  FailureThreshold: 3
readinessProbe:

  scheme: HTTPS
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5

