############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################


apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mm5
  namespace: mep
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "{{ .Values.networkIsolation.phyInterface.mm5 }}",
      "mode": "bridge",
      {{- if eq .Values.networkIsolation.ipamType "whereabouts" }}
      "ipam": {
        "type": "whereabouts",
        "datastore": "kubernetes",
        "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
        "range": "100.1.1.25/24",
        "range_start": "100.1.1.25",
        "range_end": "100.1.1.254",
        "log_file" : "/tmp/whereabouts.log",
        "gateway": "100.1.1.1"
      }
      {{- else }}
      "ipam": {
         "type": "host-local",
         "subnet": "100.1.1.0/24",
         "rangeStart": "100.1.1.25",
         "rangeEnd": "100.1.1.254",
         "routes": [
           { "dst": "0.0.0.0/0" }
         ],
         "gateway": "100.1.1.1"
       }
       {{- end }}
    }'
